# Generated by Django 4.2.3 on 2024-09-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currencies",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "currency",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(max_length=3)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Money_Scan",
            fields=[
                ("scanId", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="./mediafiles")),
                ("denomination", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MoneyRecogniser.currencies",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Denominations",
            fields=[
                ("denominationID", models.AutoField(primary_key=True, serialize=False)),
                ("denomination", models.IntegerField()),
                ("description", models.CharField(max_length=1000)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MoneyRecogniser.currencies",
                    ),
                ),
            ],
        ),
    ]
