# Generated by Django 4.2.3 on 2024-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MoneyRecogniser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencies",
            name="name",
        ),
        migrations.RemoveField(
            model_name="denominations",
            name="denominationID",
        ),
        migrations.AddField(
            model_name="denominations",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
